<Project>
	<PropertyGroup>


		<RootNamespace>$(MSBuildProjectName)</RootNamespace>
		<AssemblyName>$(MSBuildProjectName)</AssemblyName>

		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AnalysisLevel>latest</AnalysisLevel>
		<AnalysisMode>All</AnalysisMode>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

		<NoWarn>$(NoWarn);CA1515;CA1819;CA2007;CA1861;CA1062;CA1848;CA1031;CA1002</NoWarn>
	</PropertyGroup>
</Project>