<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.12" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AgenticEngineering.Application\AgenticEngineering.Application.csproj" />
    <ProjectReference Include="..\AgenticEngineering.Domain\AgenticEngineering.Domain.csproj" />
  </ItemGroup>
</Project>
